<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $subject }}</title>
</head>
<body style="margin:0;padding:0;background-color:#f3f7fb;font-family:Arial,Helvetica,sans-serif;color:#10243f;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:linear-gradient(160deg,#edf5ff 0%,#f7fbff 45%,#fffdf6 100%);padding:28px 12px;">
        <tr>
            <td align="center">
                <table role="presentation" width="640" cellspacing="0" cellpadding="0" style="max-width:640px;width:100%;background:#ffffff;border:1px solid #dfe9f5;border-radius:16px;overflow:hidden;box-shadow:0 12px 28px rgba(16,36,63,0.08);">
                    <tr>
                        <td style="padding:22px 28px;background:linear-gradient(130deg,#0b3b7a 0%,#1365b0 58%,#1a8bd2 100%);color:#ffffff;">
                            <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td style="vertical-align:middle;">
                                        <p style="margin:0;font-size:12px;letter-spacing:1.6px;text-transform:uppercase;opacity:0.88;">Road Transport Department</p>
                                        <h1 style="margin:8px 0 0;font-size:24px;line-height:1.25;font-weight:800;">JPJFit Certificate Issued</h1>
                                    </td>
                                    <td align="right" style="vertical-align:middle;">
                                        @php
                                            $logoPath = public_path('images/jpjfit_logo.png');
                                            $logoSrc = (isset($message) && file_exists($logoPath))
                                                ? $message->embed($logoPath)
                                                : asset('images/jpjfit_logo.png');
                                        @endphp
                                        <img src="{{ $logoSrc }}" alt="JPJFit" style="display:block;width:72px;height:auto;border-radius:10px;background:rgba(255,255,255,0.15);padding:6px;">
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:26px 28px 8px;">
                            <p style="margin:0 0 10px;font-size:16px;line-height:1.6;">Hello {{ $participantName }},</p>
                            <p style="margin:0 0 14px;font-size:15px;line-height:1.7;color:#2b4564;">
                                Congratulations. Your UKJK certificate is ready, and the official PDF is attached to this email.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:6px 28px 16px;">
                            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:separate;border-spacing:0;border:1px solid #dbe6f3;border-radius:12px;overflow:hidden;">
                                <tr>
                                    <td style="padding:12px 14px;background:#f5faff;font-size:12px;font-weight:700;color:#4a6788;text-transform:uppercase;letter-spacing:0.8px;width:44%;">Certificate Number</td>
                                    <td style="padding:12px 14px;background:#ffffff;font-size:14px;font-weight:700;color:#0d3767;">{{ $certificateNo }}</td>
                                </tr>
                                <tr>
                                    <td style="padding:12px 14px;background:#f5faff;font-size:12px;font-weight:700;color:#4a6788;text-transform:uppercase;letter-spacing:0.8px;">Session</td>
                                    <td style="padding:12px 14px;background:#ffffff;font-size:14px;color:#274666;">{{ $sessionCode }}</td>
                                </tr>
                                <tr>
                                    <td style="padding:12px 14px;background:#f5faff;font-size:12px;font-weight:700;color:#4a6788;text-transform:uppercase;letter-spacing:0.8px;">Issued Date</td>
                                    <td style="padding:12px 14px;background:#ffffff;font-size:14px;color:#274666;">{{ $issuedAt }}</td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:6px 28px 26px;">
                            <div style="padding:12px 14px;background:#fff8e8;border:1px solid #f6ddb0;border-radius:10px;font-size:13px;line-height:1.6;color:#7a5a21;">
                                This message is auto-generated by {{ $appName }}. Please keep the attached certificate PDF for your official records.
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:18px 28px;background:#f8fbff;border-top:1px solid #e2ecf7;">
                            <p style="margin:0;font-size:12px;line-height:1.7;color:#607b99;">
                                {{ $appName }}<br>
                                Official Fitness Assessment System
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
